whatlies/common.py, whatlies/embedding.py, whatlies/embeddingset.py, whatlies/language.py
Function added to common.py and to embeddingset.
I also added an option of choosing the distance metric you want to use. I couldn't find any other layouts that allowed for a distance input.
=> Adding plot_graph_layout

.gitignore, setup.py, tests/test_embedding.py, tests/test_transformers.py, whatlies/embedding.py, whatlies/embeddingset.py, whatlies/transformers/addrandom.py, whatlies/transformers/common.py, whatlies/transformers/noise.py, whatlies/transformers/pca.py, whatlies/transformers/umap.py
This bugfix ensures that properties remain, even after a transformation.
=> Property bugfix

docs/index.md, readme.md, tests/test_embedding.py, tests/test_embeddingset.py, tests/test_transformers.py, whatlies/common.py, whatlies/embedding.py, whatlies/embeddingset.py, whatlies/language.py, whatlies/transformers/common.py, whatlies/transformers/noise.py
fix for https://github.com/RasaHQ/whatlies/issues/24
=> similarity feature

setup.py
=> Remove duplicate package from test dependencies

Makefile
As the title says and discussed in related issues (#62, #64).
=> Fix #62, Fix #64: makefile corrections

setup.py, tests/prepare_fasttext_tests.py, tests/test_countvector_lang.py, tests/test_embeddingset.py, tests/test_fasttext_lang.py, tests/test_pblang.py, tests/test_sklearn/test_countvector_sklearn.py, tests/test_sklearn/test_fasttext_sklearn.py, tests/test_sklearn/test_spacy_sklearn.py, tests/test_spacy_language.py, whatlies/language/__init__.py, whatlies/language/bpemblang.py, whatlies/language/common.py, whatlies/language/countvector_lang.py
These are the formatting changes by `black` after running `pre-commit run --all-files`.
=> Run black pre-commit hook on all files

mkdocs.yml, tests/test_embedding.py, tests/test_lang/test_countvector_lang.py, whatlies/embedding.py, whatlies/language/bpemblang.py, whatlies/language/countvector_lang.py, whatlies/language/gensim_lang.py
Two new features added. Small ones, but useful.
=> Embedding features

whatlies/embeddingset.py
=> Remove code duplication

whatlies/language/spacy_lang.py
=> Fix typos; improve wording

.github/workflows/pythonpackage.yml
Adding Mac-OS as a testing target.
=> added-macos-tests

setup.py
With tensorflow 2.3 out there, we should see a lot of our issues fixed.
=> changed-dependencies

setup.py, tests/test_transformers.py, whatlies/transformers/__init__.py, whatlies/transformers/ivis.py
Hi, 
due to some problems, I decided to start over from a new branch. I installed whatlies with make develop, installed pre-commit hooks and ran black formatting on files that I've changed. All tests are passing locally.
=> Ivis Transformer Implementation

.github/workflows/pythonpackage.yml
=> Upgrade setuptools and wheel in github actions workflow

tests/test_sklearn/test_simple_pipeline.py
I was wondering if the scikit-learn implementation is robust against duplicates (which can totally happen). So I extended the test to confirm.
=> Extra Sklearn Test

tests/test_embeddingset.py, whatlies/embeddingset.py
Fixes #124, as the title says.
=> Fix #124 - Allow one Embedding to be passed to EmbeddingSet constructure

tests/test_embeddingset.py, whatlies/embeddingset.py
Added a simple `pipe` method. Fixes https://github.com/RasaHQ/whatlies/issues/130
=> Add Pipe Method

whatlies/transformers/addrandom.py, whatlies/transformers/ivis.py, whatlies/transformers/noise.py, whatlies/transformers/opentsne.py, whatlies/transformers/pca.py, whatlies/transformers/tsne.py, whatlies/transformers/umap.py
=> Fix #153 - Return self in fit method of transformers

tests/test_embeddingset.py, whatlies/embeddingset.py
This PR fixes #161 and fixes #162.
=> Fix #161,#162 - Add to_names_X and from_names_X methods to EmbeddingSet

.github/workflows/dependencies.yml, docs/index.md, docs/tutorial/languages/index.md, setup.py, whatlies/language/__init__.py
https://github.com/RasaHQ/whatlies/issues/133
=> Fix #133: Move Sense2Vec as an Optional Dependency

tests/test_transformers.py, whatlies/transformers/__init__.py, whatlies/transformers/normalizer.py
This PR fixes #150 by implementing `Normalizer` transformer for normalizing embeddings in an `EmbeddingSet` instance.
=> Fix #150 - Add Normalizer transformer

whatlies/embeddingset.py
This PR addresses issues #125 and #127 for Altair plots, i.e. `plot_interactive`. The changes are all backwards compatible (including the axes labels, text of title as well as the logic for removing axes vectors; although, for the last one it might have side effects, e.g. an embedding with name "Dimension 0" would be removed if axis is set to 0).
@koaning It seems the `plot_interactive` is not tested at all in the test suit. So I just complied and didn't add any tests and instead manually tested the changes to make sure they are working. Do you have any specific plan for adding the tests for this method?
=> Add support for integer axis, axis labels and title for `plot_interactive`

whatlies/embeddingset.py
This PR sets the default value of `axes` in `plot_interactive_matrix` method to `[0, 1]` as [discussed here](https://github.com/RasaHQ/whatlies/pull/188#issuecomment-685446261). Also, it adds the support for integer and `Embedding` type axes to this method (e.g. we can use `embset.plot_interactive_matrix(0, 'foo', bar)`). It was manually tested and worked fine.
=> Set default value of `axes` and add support for integer and Embedding axes in `plot_interactive_matrix`

readme.md
Added citation info (Bibtex entry) and a link to the arXiv paper to `readme.md`.
=> Citation Info

whatlies/embeddingset.py
This PR removes some of the redundancies in altair plot methods when annotating data points with texts.
=> Remove redundancies from altair plot methods

tests/test_plotting/test_matplotlib/test_embedding_plot.py, tests/test_plotting/test_matplotlib/test_embeddingset_plot.py
This PR fixes #217 by adding `__init__.py` files to the test directories.
**Note:** We have not put the source code in a `src` directory (at least, not yet!).
---
**TODOs**:
---
=> Fix #217 - Add `__init__.py` files to test directories

.flake8, docs/tutorial/embeddings/index.md, docs/tutorial/observations/index.md, tests/test_lang/test_hftransformers_lang.py, whatlies/language/_convert_lang.py, whatlies/language/_tfhub_lang.py, whatlies/transformers/_ivis.py, whatlies/transformers/_pca.py, whatlies/transformers/_tsne.py, whatlies/transformers/_umap.py
This PR fixes some style and formatting issues. Specifically, it fixes some of the issues reported by running `make flake` and also includes the fixes done after running `pre-commit run --all-files`.
=> Fix some formatting and style issues

docs/releases.md, setup.py, whatlies/__init__.py
=> new-version-0.5.2

docs/tutorial/scikit-learn.md
=> Minor edit to scikit-learn docs.

tests/test_transformers.py
This is a temporary measure while we wait for a fix for https://github.com/tqdm/tqdm/issues/1037.
=> Turn Off Ivis Tests

whatlies/language/_gensim_lang.py
I've added a section on downloading GloVe embeddings via the gensim api.
=> Downloading Gensim - Docs Update

.github/workflows/dependencies.yml, docs/api/language/sentence_tfm.md, docs/tutorial/scikit-learn.md, mkdocs.yml, setup.py, tests/test_sklearn/test_simple_pipeline.py, whatlies/__init__.py, whatlies/language/__init__.py, whatlies/language/_sentencetfm_lang.py
Add support for [this project](https://www.sbert.net/docs/pretrained_models.html). Addresses https://github.com/RasaHQ/whatlies/issues/250.
=> Add Support for Sentence Transformers

.github/workflows/croncheck.yml, .github/workflows/dependencies.yml, .github/workflows/pythonpackage.yml, .github/workflows/rasatest.yml, .github/workflows/stylecheck.yml, .gitignore, Makefile, docs/api/language/diet.md, mkdocs.yml, setup.py, tests/rasa-test-demo/actions/actions.py, tests/rasa-test-demo/config.yml, tests/rasa-test-demo/credentials.yml, tests/rasa-test-demo/data/nlu.yml, tests/rasa-test-demo/data/rules.yml, tests/rasa-test-demo/data/stories.yml, tests/rasa-test-demo/domain.yml, tests/rasa-test-demo/endpoints.yml, tests/rasa-test-demo/tests/test_stories.yml, tests/test_lang/test_rasa_lang.py, tests/test_sklearn/test_simple_pipeline.py, whatlies/language/__init__.py, whatlies/language/_diet_lang.py
This PR adds support for DIET embeddings. It's not just DIET ... it's the output from the entire pipeline ... but it can still be useful to play around with. This PR fixes https://github.com/RasaHQ/whatlies/issues/248.
=> Add support for DIETLanguage

docs/releases.md, setup.py, whatlies/language/_common.py
This will allow for more pipelines to support.
=> partial-fit support

docs/index.md, docs/tutorial/embeddingsets/index.md, docs/tutorial/embeddingsets/tut-chart-color.json, docs/tutorial/embeddingsets/tut-chart-hover.json, readme.md, tests/test_embeddingset.py, tests/test_plotting/test_altair/test_embeddingset_plot_interactive.py, whatlies/embeddingset.py
Fixes https://github.com/RasaHQ/whatlies/issues/286
=> Remove Correlation Plot + Add Brush Feature

readme.md
updated paper link and citations to the published version of the paper
=> Citation update

docs/faq.md, docs/interactive1.js, docs/interactive2.js, docs/tutorial/embeddingsets/index.md, docs/tutorial/embeddingsets/tut2-chart1.json, docs/tutorial/embeddingsets/tut2-chart2.json, docs/tutorial/embeddingsets/tut2-chart3.json, docs/tutorial/embeddingsets/tut2-chart4.json, docs/tutorial/embeddingsets/tut2-chart5.json, docs/tutorial/embeddingsets/tut2-chart6.json, tests/test_plotting/test_matplotlib/test_plot_3d.py, tests/test_transformers.py, whatlies/embeddingset.py, whatlies/transformers/_addrandom.py, whatlies/transformers/_noise.py, whatlies/transformers/_normalizer.py, whatlies/transformers/_pca.py
Fixed all the typos where blue was written as bluee mentioned on this issue code #177
=> fixed small typos

tests/test_sklearn/test_simple_pipeline.py, whatlies/language/_common.py
Am still working on some tests as well.
=> Turn NaN into zeros.

whatlies/embeddingset.py
We need to be mindful of args vs. kwargs now.
=> Fix sklearn test
