RasaHQ/whatlies

- Makefile
- docs/api/language/s2v_lang.md
- docs/tutorial/languages/index.md
- notebooks/03-interactive-transformations.ipynb
- notebooks/05-language-backends.ipynb
- whatlies/language/__init__.py
- whatlies/language/sense2vec_lang.py
- whatlies/language/spacy_lang.py
I must admit, this is not the most impactful PR 😁 but I'm in kurzarbeit today and I was reading your codebase and on the way I noticed this typo. So I fix it, I built the docs and ran the tests. and here am I.
Btw, congrats on that repo setup. It's so clean, it makes contributing / reading a breeze. Even down to the API of the makefile. Definitely going to try to emulate some of that in my repos going forward.
One remark though, it's a one time thing, but 
```sh
python -m spacy download en_core_web_sm
```
is missing from docs and the `make develop` command. Without that the notebook tests fail.
What are your thoughts on that? 
Note: I couldn't make tests pass for notebook 5 (I don't have the `../s2v_old/` folder). The rest is ✅
> Fix typo and make tests pass on clean dev env

- readme.md
Fixes the import statement in the README snippet.
```python
from whatlies.language.language import SpacyLanguage # ❌ ModuleNotFoundError: No module named 'whatlies.language.language'
from whatlies.language import SpacyLanguage # ✅
```
> Correct import statement

- .pre-commit-config.yaml
This PR removes the `files` option of `black` hook so that all the code files, including tests, would be checked by `black`.
The repo needs to be checked by `black` since none of the files have been checked so far; but I think it's better to put that in another PR (if needed).
> Fix #63: Remove files option of black pre-commit hook

- tests/test_transformers.py
Since `nlp.vocab` or `vocab` in spaCy is just a cache of used tokens, therefore when the vocab or language is loaded from disk the `vocab` would be empty and therefore iterating over it would result in an empty list (as a result the `words` list would be empty as well). That's why currently 11 transformers tests fail. Instead, we need to use `vocab.strings` and iterate over that.
Also keep in mind that when you persist a `Vocab` or `Language` instance in spaCy, another special string denoted as `'_SP'` is automatically added to the list of strings in the vocab (see [here][1] or [here][2]).
[1]: https://github.com/RasaHQ/whatlies/blob/2783be06fcc2ccea01fd17da9cabfc7f3aacb987/tests/custom_test_vocab/strings.json#L29
[2]: https://github.com/RasaHQ/whatlies/blob/2783be06fcc2ccea01fd17da9cabfc7 …
> Fix error in transformers test file

- whatlies/embeddingset.py
Currently, when a `tuple` or a `list` is used for getting items from an `EmbeddingSet` instance, it would return all the embeddings. This PR fixes this issue, so that a new `EmbeddingSet` is returned **containing only the requested embeddings**.
> Fix EmbeddingSet getitem method

- whatlies/embeddingset.py
To get the overlap, `intersection` should be used instead of `union`.
> Fix bug in movement_df method

- tests/test_lang/test_spacy_language.py
- whatlies/language/spacy_lang.py
This PR is a (temporary) fix for issue #91 which resulted from doing tokenization based on whitespace. I thought this was important to be fixed (until we find a better solution) because, as discussed in #91, even for some sentences (and languages with no space, such as Japanese) where there is no requested context embedding, the result is wrong as well.
@koaning I have used `en_core_web_md` model in the tests so that we could have better and more reliable real use-case tests. However, I did not add the installation command to Github actions config file yet (that's why the tests are failing) because I don't know if you are agreed with this or not. Let me know if you are OK with this, and I'll add another commit to this PR for that.
> Fix incorrect embedding bug in spaCy language class

- tests/test_embeddingset.py
This PR fixes the infamous(!) flaky test. Considering the embedding vectors in `lang`, instead of `cosine` we use `euclidean` as the distance metric to prevent similarity error due to happenstance.
> Fix flaky test of embeddingset

- setup.py
- tests/test_lang/test_hftransformers_lang.py
- whatlies/language/__init__.py
- whatlies/language/hftransformers_lang.py
This PR addresses #12 and implements `HFTransformersLanguage` class to support Hugging Face Transformer models. It's an initial implementation, with room for adding more features and custom configs. Currently, the embedding vector is obtained by summing the token representations (excluding special tokens, e.g. [CLS] or [SEP]).
Further, we have added `torch` as a **development dependency** so that we can test this class on both TensorFlow as well as PyTorch.
> Add Hugging Face Transformers language class

- .flake8
- tests/test_lang/test_tfhub_lang.py
- whatlies/language/__init__.py
- whatlies/language/tfhub_lang.py
This PR addresses issue #40. It provides (an initial) support for text-embedding models in TensorFlow Hub (or any other compatible model which could be loaded using `hub.load()`). Note that this only supports models which can operate/be called directly on raw text/sentence string; therefore, for the time being, it does not support models like BERT ([example](https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2)) which need additional pre-processing steps.
> Add support for TF Hub text-embedding models

- tests/test_lang/test_convert_lang.py
- whatlies/language/convert_lang.py
This PR improves `ConveRTLanguage` class implementation by adding the support for different ConveRT models and signatures. It also includes the relevant tests to ensure it's working properly for different configurations (although, this comes at the cost of longer running time of tests since the models should be downloaded and are rather large).
> Add support for different ConveRT models and signatures

- whatlies/embeddingset.py
The following raises an error:
```python
foo = Embedding('foo',...)
bar = Embedding('bar',...)
baz = Embedding('baz',...)
embset = EmbeddingSet(foo, bar)
embset.score_similar(baz, n=2)
> ValueError: Embedding for `baz` does not exist in this EmbeddingSet
```
Only if the given embedding is a string it should be checked whether it exists in `EmbeddingSet` or not. Otherwise, an `Embedding` instance is always allowed.
> Fix bug in score_similar method of EmbeddingSet

- setup.py
- whatlies/language/spacy_lang.py
As the title says. However, there are two additional points:
- Instead of loading all the vocab when instantiating the class (i.e. in `__init__` method), I decided to implement a separate method for this in order to comply with the  original goal of spaCy maintainers which is reducing the loading time of the model (in this library, this point is useful when the user only want to get embeddings from the model, and not doing something like similarity search). Although, in this implementation, this reduction may come at the annoyance of calling `self._load_vocab` method every time we want to iterate over `vocab` in the code (which currently happens only once).
- I have not included a spaCy model (e.g. `en_core_web_md`) in the tests yet, until it's decided how to go about this; however, I …
> Fix #101 - update SpacyLanguage class to support spaCy v2.3+ models

- whatlies/common.py
- whatlies/embedding.py
- whatlies/embeddingset.py
This PR addresses #38 for matplotlib plots (i.e. `plot` method of `Embedding` and `EmbeddingSet`).
> Add axis_option argument for matplotlib plots

- .github/workflows/pythonpackage.yml
- tests/test_transformers.py
I reduced the number of `epochs` that Ivis is using during testing. That should help with some of the flaky tests. 
I also ran a benchmark on that file with pytest locally. 
```
> pytest tests/test_transformers.py --durations 0
16.48s call     tests/test_transformers.py::test_transformations_new_size[OpenTsne]
15.63s call     tests/test_transformers.py::test_transformations_keep_props[transformer4]
6.96s call     tests/test_transformers.py::test_transformations_new_size[Umap0]
2.06s call     tests/test_transformers.py::test_transformations_keep_props[transformer5]
1.97s call     tests/test_transformers.py::test_transformations_keep_props[transformer0]
1.91s call     tests/test_transformers.py::test_transformations_new_size[Ivis1]
1.90s call …
```
> Reduce Ivis Bugs during Testing

- tests/test_embeddingset.py
- whatlies/embeddingset.py
Fixes #128, as the title says.
> Fix #128 - Use 'EmbSet' as the default name of EmbeddingSet

- tests/test_transformers.py
The automated tests for the last push [were failed](https://github.com/RasaHQ/whatlies/runs/986783620) after 5+ hours due to the Ivis not converging (as known before). This PR fixes another instance.
> Reduce Ivis epochs in tests

- .github/workflows/croncheck.yml
- .github/workflows/pythonpackage.yml
- setup.py
This PR updates `croncheck` workflow as follow:
- Adds Python 3.6
- Removes OS specific installation
- Adds `en_core_web_sm` installation ([last check was failed due to this](https://github.com/RasaHQ/whatlies/runs/987110923))
- Removes Pytorch installation (also for `pythonpackage` workflow)
- Removes redundant `flake8` installation (also for `pythonpackage` workflow)
And also adds `torch` as a test dependency in `setup.py`.
> Update Github Actions workflow files

- whatlies/embedding.py
My gut feeling is that the main utility for the `.plot()` method on the `Embedding` object is that we can easily demonstrate how this package allows for arithmetic. That means that the chart is educational in nature. It also means that we might favor `arrow` as a default argument over `scatter`. 
This is a breaking change, so we should not immediately do this change without discussion. I've created this PR as a place to discuss it and I won't merge unless I've hear another opinion on this. 
@mkaze do you have a strong opinion on this?
> Make the Embedding.plot() method use `arrow` as a standard. 

- tests/test_transformers.py
- whatlies/transformers/__init__.py
- whatlies/transformers/addrandom.py
- whatlies/transformers/ivis.py
- whatlies/transformers/noise.py
- whatlies/transformers/opentsne.py
- whatlies/transformers/pca.py
- whatlies/transformers/transformer.py
- whatlies/transformers/tsne.py
- whatlies/transformers/umap.py
This PR fixes #154 by adding an abstract base class for transformers and also performing some refactoring (i.e. removing `__call__` method implementation from subclasses).
> Fix #154 - Add base class for transformers

- .github/workflows/croncheck.yml
The scheduled tests [are failing](https://github.com/RasaHQ/whatlies/actions?query=workflow%3A%22Cron+Test+Dependencies%22) due to this.
> Add missing spacy model to croncheck

- tests/test_embeddingset.py
- whatlies/embeddingset.py
To adress https://github.com/RasaHQ/whatlies/issues/134 we're now doing some extra checks and also raising a `ValueError` if there's vectors with a different shape.
> Fix #134: Check EmbeddingSet Input

- whatlies/transformers/addrandom.py
- whatlies/transformers/common.py
- whatlies/transformers/ivis.py
- whatlies/transformers/noise.py
- whatlies/transformers/normalizer.py
- whatlies/transformers/opentsne.py
- whatlies/transformers/pca.py
- whatlies/transformers/tsne.py
- whatlies/transformers/umap.py
This PR does some refactoring in transformers:
- `embset_to_X` method was removed and instead `to_names_X` method is used.
- Some redundant calls in `fit` method of `Noise` and `AddRandom` were removed.
> Refactor transformers - replace embset_to_X with to_names_X

- tests/test_embedding.py
- tests/test_embeddingset.py
- whatlies/embedding.py
- whatlies/embeddingset.py
This PR fixes #122 by adding a `ndim` attribute for `Embedding` class to represent the dimension of embedding vector.
@koaning I did not add this for `EmbeddingSet` since I think you were not in favor of it as discussed in #122. Anyways, the way to implement it would be:
```python
@property
def ndim(self):
return self.embeddings.values()[0].ndim
```
> Fix #122 - Add ndim attribute for Embedding and EmbeddingSet

- whatlies/transformers/ivis.py
> Fix #172 - Use `transform` method instead of `fit_transform` in Ivis transformer

- tests/test_plotting/test_matplotlib/test_embedding_plot.py
- whatlies/embedding.py
- whatlies/embeddingset.py
This PR changes the default value of `x_axis` and `y_axis` arguments in `plot` and `plot_interactive` methods.
**Backwards incompatible changes:**
- With 2D embeddings, when using `Embedding.plot` or `EmbeddingSet.plot` without setting `x_axis` and `y_axis`, the default axis labels would be "Dimension 0" and "Dimension 1" (instead of "x" and "y").
- With 2D embeddings, when using `Embedding.plot` or `EmbeddingSet.plot`, the `x_axis` and `y_axis` arguments no longer can take `None` value (the previous default value).
> Change default axis value of plot methods

- tests/test_plotting/test_matplotlib/test_embedding_plot.py
- tests/test_plotting/test_matplotlib/test_embeddingset_plot.py
- whatlies/embedding.py
- whatlies/embeddingset.py
This PR partially addresses #129 by adding support for custom axis metrics in matplotlib plots (i.e. `plot` method).
---
**TODO**:
---
> Fix #129 - Add support for alternative axis metrics in `plot` method

- tests/test_embeddingset.py
- whatlies/embeddingset.py
This PR partially addresses #129 by adding support for custom axis metric in Altair plot methods. To make the implementation easier, we added a new optional argument for `EmbeddingSet.compare_against` method to take custom functions.
**Update**: The `EmbeddingSet.compare_against` were refactored to use the already present argument for handling custom functions as well.
---
**TODO**:
---
> Fix #129 - Add support for alternative axis metrics in Altair plot methods

- whatlies/embeddingset.py
This PR fixes #206 by removing `show_axis_point` argument from `plot_interactive` and `plot_interactive_matrix` methods.
---
**TODOs**:
---
**Backwards incompatible changes:**
- Previously, the default value of this argument was `False`. Therefore, the axis vectors were not included in the plot by default. This is no longer the case.
> Fix #206 - Remove `show_axis_point` argument from plot methods

- whatlies/embeddingset.py
My bad! This PR adds the missing backticks to the docstrings of `to_names_X` and `from_names_X` methods.
> Add missing backticks to docstrings

- tests/test_plotting/test_matplotlib/test_plot_3d.py
- whatlies/embedding.py
- whatlies/embeddingset.py
This adresses https://github.com/RasaHQ/whatlies/issues/200. 
```python
emb.transform(Pca(3)).plot_3d(annot=True)
```
```python
emb.transform(Pca(3)).plot_3d("king", "dude", "green", annot=True)
```
There's a few things about this PR worth discussing. 
1. The color property works differently in 3d charts. It seems as if the color is automatically altered depending on the depth of the point. Since this is a sensible way of dealing with it I'm wondering if this is something we want to influence directly. 
2. I'm currently adding an absolute value to offset the text from the 3d point. It kind of works but it depends on the zoom level. @mkaze might this be better as an argument? 
3. It feels like we might be able to generalise the plots. They always have a phase where a DataFrame is created …
> Adding 3D-Plot #200

- whatlies/embeddingset.py
This PR removes the redundant `text` property used in `plot_interactive_matrix`.
> Remove redundant text property in `plot_interactive_matrix`

- tests/test_embeddingset.py
- whatlies/embedding.py
- whatlies/embeddingset.py
This PR fixes https://github.com/RasaHQ/whatlies/issues/155. I've left the `add_property` intract since it's not hurting anyone but I have changed the internals of `embedding` slighty. I added a `copy()` command such that we have a convenient method to get a copy of the embedding that also has all of the properties attached. 
The api currently works swell but this PR is making me wonder if in the future, we may want to not have properties added to the `Embedding` interactively since it might be more used friendly to add all of these custom properties in a `data` field on the `Embedding`. Technically, currently a user can `embset.assign(vector=lambda d: 1)` and it'd be no bueno. 
@mkaze got thoughts on this? I'll gladly make an issue for this if you feel the same way.
> Add .assign verb #155

- tests/test_plotting/test_altair/common.py
- tests/test_plotting/test_altair/test_embeddingset_plot_interactive.py
- tests/test_plotting/test_altair/test_embeddingset_plot_interactive_matrix.py
This PR partially addresses #183 by adding tests for `plot_interactive` and `plot_interactive_matrix`. The `plot_movement` method would be addressed in another PR because the method needs some changes.
---
**TODOs:**
---
> Add tests for Altair plot methods, `plot_interactive` and `plot_interactive_matrix`

- whatlies/embeddingset.py
The missing indentation caused the second sentence to not be shown in the method [documentation](https://rasahq.github.io/whatlies/api/embeddingset/#whatlies.embeddingset.EmbeddingSet.assign).
> Fix a minor error in `assign` method docstring

- tests/test_embedding.py
- whatlies/embedding.py
I wanted to do:
```python
lang.score_similar(-lang['blue'])
```
But this caused an error. I figured adding `__neg__` is helpful. Allows for more "playfullness".
> Minor Feature: Add Negation Operator to Embedding

- whatlies/language/_convert_lang.py
It seems that the ConveRT models' URLs [have been recently changed](https://github.com/PolyAI-LDN/polyai-models/commit/ef5c0be03a361f093b2924bf62f35b100497c19d). This PR updates them to the new URLs.
As a side note, this is the root cause of the failure in automated tests in #234.
---
**TODOs:**
---
> Update ConveRT models' URLs

- tests/test_embeddingset.py
- whatlies/embeddingset.py
This PR tries to adress https://github.com/RasaHQ/whatlies/issues/228. We now allow for this; 
```python
from whatlies.embeddingset import EmbeddingSet
foo = Embedding("foo", [0.1, 0.3, 0.10])
bar = Embedding("bar", [0.7, 0.2, 0.11])
emb = EmbeddingSet(foo, bar)
emb_with_property1 = emb.assign(dim0=lambda d: d.vector[0],
dim1=lambda d: d.vector[1],
dim2=lambda d: d.vector[2])
emb_with_property2 = emb.assign(group=["foo_grp", "bar_grp"])
emb_with_property3 = emb.assign(constant=1)
```
Note that we will throw an error if we were to do; 
```python
emb_with_property4 = emb.assign(group=["foo_grp", "bar_grp", "dimension_misalign"])
```
> #228 Assign should accept Values

- whatlies/language/_bpemblang.py
- whatlies/language/_countvector_lang.py
- whatlies/language/_gensim_lang.py
- whatlies/language/_hftransformers_lang.py
- whatlies/language/_sense2vec_lang.py
- whatlies/language/_tfhub_lang.py
- whatlies/language/_tfidf_lang.py
I noticed a lot of warnings containing; 
```
/home/vincent/Development/whatlies/venv/lib/python3.8/site-packages/sklearn/base.py:209: 
FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter 
cannot be retrieved as an instance attribute. Previously it would return None.
```
So after a quick [investigation](https://stackoverflow.com/questions/63251437/futurewarning-get-params-from-scikit-learn) I found the fix for it. This also makes the library robust on the new sklearn version.
> Scikit-Learn 0.24 Compatilibity

- whatlies/embeddingset.py
Panning and Zooming seems useful even for selection kind of plots especially when we have a lot of dense points to select from.
Adding this functionality (when shift key is held) to `plot_brush` method
> Add pan and zoom functionality to plot_brush

- whatlies/embeddingset.py
Small suggestion to improve the readability of the brush plot.
Now you can als see to which group the ranked text belongs.
This is particularly helpful when your embedding+dimension reduction method isn't able to separate the different groups.
Current situation:
Proposal:
> add color ranked text in plot brush
